Repository navikt/crm-hot-tolk, pull requests merged in 2022-04, with the labels that each got.

#1196 TOLK-1852: Kobling til bruker via tlf nummer feiler --> master
  force-app/main/accessControl/classes/HOT_RequestRoutingHandler.cls
  force-app/main/default/objects/Person__c/fields/HOT_MobilePhoneStripped__c.field-meta.xml
  force-app/main/default/permissionsets/HOT_Admin.permissionset-meta.xml
  force-app/main/default/permissionsets/HOT_Config.permissionset-meta.xml
Labels: Needs thorough testing

#1213 TOLK - 1956 - Som bestiller ønsker jeg å kunne sende inn en bestilling som går over midnatt
  force-app/main/userCommunity/lwc/hot_recurringTimeInput/hot_recurringTimeInput.js
Labels: Ready to merge

#1193 Tolk 1795 - Som tolkebruker skal jeg miste tilgangen til info på bestilling etter 1 år
  force-app/main/default/classes/HOT_InterpreterOnWorkOrderService.cls
  force-app/main/default/classes/HOT_InterpreterOnWorkOrderService.cls-meta.xml
  force-app/main/default/classes/HOT_InterpreterOnWorkOrderServiceTest.cls
  force-app/main/default/classes/HOT_InterpreterOnWorkOrderServiceTest.cls-meta.xml
  force-app/main/default/lwc/mineBestillingerWrapper/mineBestillingerWrapper.html
  force-app/main/triggers/classes/HOT_AssignedResourceHandler.cls
  force-app/main/triggers/classes/HOT_AssignedResourceHandlerTest.cls
  force-app/main/triggers/classes/HOT_ContentDocumentLinkHandlerTest.cls
  force-app/main/triggers/classes/HOT_ServiceAppointmentHandler.cls
  force-app/main/userCommunity/classes/HOT_WorkOrderListController.cls
  force-app/scratch-org/layouts/ServiceAppointment-Service Appointment Layout.layout-meta.xml
  force-app/scratch-org/layouts/ServiceResource-Service Resource Layout.layout-meta.xml
Labels: Needs thorough testing

#1218 Revert "Tolk 1795 - Som tolkebruker skal jeg miste tilgangen til info på bestilling etter 1 år"
  force-app/main/default/classes/HOT_InterpreterOnWorkOrderService.cls
  force-app/main/default/classes/HOT_InterpreterOnWorkOrderService.cls-meta.xml
  force-app/main/default/classes/HOT_InterpreterOnWorkOrderServiceTest.cls
  force-app/main/default/classes/HOT_InterpreterOnWorkOrderServiceTest.cls-meta.xml
  force-app/main/default/lwc/mineBestillingerWrapper/mineBestillingerWrapper.html
  force-app/main/triggers/classes/HOT_AssignedResourceHandler.cls
  force-app/main/triggers/classes/HOT_AssignedResourceHandlerTest.cls
  force-app/main/triggers/classes/HOT_ContentDocumentLinkHandlerTest.cls
  force-app/main/triggers/classes/HOT_ServiceAppointmentHandler.cls
  force-app/main/userCommunity/classes/HOT_WorkOrderListController.cls
  force-app/scratch-org/layouts/ServiceAppointment-Service Appointment Layout.layout-meta.xml
  force-app/scratch-org/layouts/ServiceResource-Service Resource Layout.layout-meta.xml
Labels: Priority
